/**
 * Redirecciones permanentes de la web antigua (WordPress/WooCommerce en
 * rtbunker.com) a la nueva. Google tiene indexadas las URLs viejas: sin esto,
 * el día del cambio de dominio todas darían 404 y se perdería el posicionamiento.
 *
 * Generado a partir de los sitemaps de la web antigua (product, product_cat y
 * page) cruzados con los handles de Medusa: 123 de 124 productos y las 26
 * categorías conservan el mismo slug.
 */

type Redirect = { source: string; destination: string; permanent: true }

/** Productos: en WooCommerce colgaban de la raíz (rtbunker.com/pegatina-x/). */
const PRODUCT_HANDLES = [
  'parasol-amg',
  'parasol-brazzers',
  'parasol-fake-taxi',
  'parasol-ford-performance',
  'parasol-gran-turismo',
  'parasol-m-performance',
  'parasol-mitsubishi-motors',
  'parasol-n-performance',
  'parasol-renault-sport',
  'parasol-seat-sport',
  'parasol-solo-fondo',
  'parasol-speed-hunters',
  'parasol-speed-hunters-japan',
  'parasol-toyotires',
  'parasolpersonalizado',
  'pegatina-500-fiat',
  'pegatina-911-porsche',
  'pegatina-abarth',
  'pegatina-airliftperformance',
  'pegatina-alpina-bmw',
  'pegatina-amg-mercedes',
  'pegatina-antisocial',
  'pegatina-antisocialdriveclub',
  'pegatina-aros-audi',
  'pegatina-bmw-motorrad',
  'pegatina-calavera-volkswagen',
  'pegatina-civic-honda',
  'pegatina-cleanculture',
  'pegatina-eat-sleep-seat-2',
  'pegatina-eclipse-mitsubishi',
  'pegatina-emblema-ford',
  'pegatina-emblema-porsche',
  'pegatina-escorpion-abath',
  'pegatina-fiat',
  'pegatina-financialmistake',
  'pegatina-ford-mustang',
  'pegatina-ford-performance',
  'pegatina-formula-one-mercedes',
  'pegatina-gsi-opel',
  'pegatina-gtr-nissan',
  'pegatina-honda',
  'pegatina-impreza-subaru',
  'pegatina-instagram',
  'pegatina-instagram-girado',
  'pegatina-john-cooper-works-mini',
  'pegatina-lagarto-audi',
  'pegatina-lagarto-quattro-audi',
  'pegatina-lancer-mitsubishi',
  'pegatina-legends',
  'pegatina-leon-peugeot',
  'pegatina-letras-audi',
  'pegatina-letras-cupra',
  'pegatina-logo-abath',
  'pegatina-logo-alpina-bmw',
  'pegatina-logo-bmw',
  'pegatina-logo-cupra-2',
  'pegatina-logo-honda',
  'pegatina-logo-mazda',
  'pegatina-logo-mercedes',
  'pegatina-logo-mercedes-2',
  'pegatina-logo-mini',
  'pegatina-logo-mitsubishi',
  'pegatina-logo-nuevo-peugeot',
  'pegatina-logo-nuevo-renault',
  'pegatina-logo-opel',
  'pegatina-logo-peugeot',
  'pegatina-logo-r-2-volkswagen',
  'pegatina-logo-r-volkswagen',
  'pegatina-logo-renault',
  'pegatina-logo-rs-ford',
  'pegatina-logo-seat-fr-2',
  'pegatina-logo-st-ford',
  'pegatina-logo-subaru',
  'pegatina-logo-toyota',
  'pegatina-logo-volkswagen',
  'pegatina-m-bmw',
  'pegatina-matricula-azul',
  'pegatina-matricula-negra',
  'pegatina-matricula-roja',
  'pegatina-mazda',
  'pegatina-mercedes-benz',
  'pegatina-miata-mazda',
  'pegatina-mitsubishi',
  'pegatina-mps-mazda',
  'pegatina-nismo-nissan',
  'pegatina-nissan',
  'pegatina-nofcksgvn',
  'pegatina-nofriendsonlyfans',
  'pegatina-noliftperformance',
  'pegatina-only-personalizada',
  'pegatina-opel',
  'pegatina-peugeot',
  'pegatina-porsche',
  'pegatina-porsche-design',
  'pegatina-porsche-motorsport',
  'pegatina-quattro-audi',
  'pegatina-rotiform',
  'pegatina-rs-renault',
  'pegatina-rtbunker',
  'pegatina-s-line-audi',
  'pegatina-sad-boyz',
  'pegatina-sad-girlz',
  'pegatina-savage',
  'pegatina-seat-sport',
  'pegatina-silvia-nissan',
  'pegatina-skyline-nissan',
  'pegatina-sti-subaru',
  'pegatina-subaru',
  'pegatina-supra-silueta-toyota',
  'pegatina-supra-toyota',
  'pegatina-toyota',
  'pegatina-trd-toyota',
  'pegatina-vlkswgn',
  'pegatina-volkswagen',
  'pegatina-vtec-honda',
  'pegatina-wrx-subaru',
  'proud',
  'tapamatriculas-akrapovic',
  'tapamatriculas-amg',
  'tapamatriculas-cupra',
  'tapamatriculas-n-performance',
  'tapamatriculas-renault-sport',
  'tapamatriculas-seat-sport',
] as const

/** Categorías: ruta anidada vieja → handle final de la categoría en Medusa. */
const CATEGORY_PATHS: Array<[string, string]> = [
  ['pegatinas', 'pegatinas'],
  ['pegatinas/banner-delantero', 'banner-delantero'],
  ['pegatinas/instagram-dorsal', 'instagram-dorsal'],
  ['pegatinas/limpiaparabrisas', 'limpiaparabrisas'],
  ['pegatinas/marcas-de-coches', 'marcas-de-coches'],
  ['pegatinas/marcas-de-coches/pegatinas-audi', 'pegatinas-audi'],
  ['pegatinas/marcas-de-coches/pegatinas-bmw', 'pegatinas-bmw'],
  ['pegatinas/marcas-de-coches/pegatinas-fiat', 'pegatinas-fiat'],
  ['pegatinas/marcas-de-coches/pegatinas-ford', 'pegatinas-ford'],
  ['pegatinas/marcas-de-coches/pegatinas-honda', 'pegatinas-honda'],
  ['pegatinas/marcas-de-coches/pegatinas-mazda', 'pegatinas-mazda'],
  ['pegatinas/marcas-de-coches/pegatinas-mercedes', 'pegatinas-mercedes'],
  ['pegatinas/marcas-de-coches/pegatinas-mini', 'pegatinas-mini'],
  ['pegatinas/marcas-de-coches/pegatinas-mitsubishi', 'pegatinas-mitsubishi'],
  ['pegatinas/marcas-de-coches/pegatinas-nissan', 'pegatinas-nissan'],
  ['pegatinas/marcas-de-coches/pegatinas-opel', 'pegatinas-opel'],
  ['pegatinas/marcas-de-coches/pegatinas-peugeot', 'pegatinas-peugeot'],
  ['pegatinas/marcas-de-coches/pegatinas-porsche', 'pegatinas-porsche'],
  ['pegatinas/marcas-de-coches/pegatinas-renault', 'pegatinas-renault'],
  ['pegatinas/marcas-de-coches/pegatinas-seatcupra', 'pegatinas-seatcupra'],
  ['pegatinas/marcas-de-coches/pegatinas-subaru', 'pegatinas-subaru'],
  ['pegatinas/marcas-de-coches/pegatinas-toyota', 'pegatinas-toyota'],
  ['pegatinas/marcas-de-coches/pegatinas-volkswagen', 'pegatinas-volkswagen'],
  ['pegatinas/parasoles', 'parasoles'],
  ['pegatinas/pegatina-matricula', 'pegatina-matricula'],
  ['pegatinas/tapamatriculas', 'tapamatriculas'],
]

/** Páginas sueltas de WordPress y rutas de WooCommerce. */
const PAGES: Array<[string, string]> = [
  ['/shop', '/es/tienda'],
  ['/shop-2', '/es/tienda'],
  ['/tienda', '/es/tienda'],
  ['/blog', '/es'],
  ['/my-account', '/es/cuenta'],
  ['/my-account/:path*', '/es/cuenta'],
  ['/mi-cuenta', '/es/cuenta'],
  ['/mi-cuenta/:path*', '/es/cuenta'],
  ['/cart', '/es/carrito'],
  ['/carrito', '/es/carrito'],
  ['/checkout', '/es/carrito'],
  ['/finalizar-compra', '/es/carrito'],
  ['/politica-de-privacidad', '/es/pagina/privacidad'],
  ['/politica-de-cookies', '/es/pagina/cookies'],
  ['/aviso-legal', '/es/pagina/aviso-legal'],
  ['/nosotros', '/es/nosotros'],
  ['/servicios', '/es/servicios'],
  ['/personalizadas', '/es/personalizadas'],
  ['/contacto', '/es/contacto'],
  // Bases que usaba WooCommerce si alguien enlazó con ellas.
  ['/producto/:slug', '/es/producto/:slug'],
  ['/product/:slug', '/es/producto/:slug'],
  ['/categoria-producto/:path*', '/es/tienda'],
  ['/product-category/:path*', '/es/tienda'],
]

export const legacyRedirects: Redirect[] = [
  ...PRODUCT_HANDLES.map((h) => ({
    source: `/${h}`,
    destination: `/es/producto/${h}`,
    permanent: true as const,
  })),
  ...CATEGORY_PATHS.map(([from, handle]) => ({
    source: `/${from}`,
    destination: `/es/categoria/${handle}`,
    permanent: true as const,
  })),
  ...PAGES.map(([source, destination]) => ({ source, destination, permanent: true as const })),
]
